//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterPanelRefined {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterPanelRefined.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Chance.
        /// </summary>
        internal static string Crit_Chance {
            get {
                return ResourceManager.GetString("Crit_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Damage.
        /// </summary>
        internal static string Crit_Damage {
            get {
                return ResourceManager.GetString("Crit_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage &amp; Mitigation.
        /// </summary>
        internal static string Damage___Mitigation {
            get {
                return ResourceManager.GetString("Damage___Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Increase.
        /// </summary>
        internal static string Damage_Increase {
            get {
                return ResourceManager.GetString("Damage_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage per 100 Pot.
        /// </summary>
        internal static string Damage_per_100_Potency {
            get {
                return ResourceManager.GetString("Damage_per_100_Potency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Hit Chance.
        /// </summary>
        internal static string Direct_Hit_Chance {
            get {
                return ResourceManager.GetString("Direct_Hit_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify character.
        /// </summary>
        internal static string ERROR_Failed_to_modify_character {
            get {
                return ResourceManager.GetString("ERROR_Failed_to_modify_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update CharacterStatus.
        /// </summary>
        internal static string ERROR_Failed_to_update_CharacterStatus {
            get {
                return ResourceManager.GetString("ERROR_Failed_to_update_CharacterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire IV GCD.
        /// </summary>
        internal static string Fire_IV_GCD {
            get {
                return ResourceManager.GetString("Fire_IV_GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCD.
        /// </summary>
        internal static string GCD {
            get {
                return ResourceManager.GetString("GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Mitigation.
        /// </summary>
        internal static string Magic_Mitigation {
            get {
                return ResourceManager.GetString("Magic_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana per Tick.
        /// </summary>
        internal static string Mana_per_Tick {
            get {
                return ResourceManager.GetString("Mana_per_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Mitigation.
        /// </summary>
        internal static string Physical_Mitigation {
            get {
                return ResourceManager.GetString("Physical_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Increase.
        /// </summary>
        internal static string Skill_Speed_Increase {
            get {
                return ResourceManager.GetString("Skill_Speed_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Properties.
        /// </summary>
        internal static string Speed_Properties {
            get {
                return ResourceManager.GetString("Speed_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  affects the rate at which your attacks and heals can critically hit as well as the damage dealt and HP restored by a critical hit.
        ///
        ///Critical Hit Rate and Damage increase by 0.1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Crit_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Crit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Hit.
        /// </summary>
        internal static string Tooltips_tooltips_Critical_Hit {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Critical_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points.
        ///You are currently wasting .
        /// </summary>
        internal static string Tooltips_tooltips_Currently_Wasting {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Currently_Wasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string Tooltips_tooltips_Defense {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  reduces physical damage taken by 1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Defense_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Defense_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determination.
        /// </summary>
        internal static string Tooltips_tooltips_Determination {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  increases damage dealt by attacks as well as HP restored by healing actions.
        ///
        ///Determination&apos;s effect increases by 0.1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Determination_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Determination_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Hit Rate.
        /// </summary>
        internal static string Tooltips_tooltips_Direct_Hit_Rate {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Direct_Hit_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  affects the rate at which your attacks can direct hit.
        ///A direct hit increases damage done by 25%.
        ///
        ///Direct Hit Rate increases by 0.1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Direct_Hit_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Direct_Hit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average damage of a 100 potency skill, including critical and direct hits as well as passive traits such as Maim and Mend.
        ///
        ///Damage is multiplied by Potency, Weapon Damage, Main Stat (Str/Int/Dex/Mnd) and all other damage modifiers (such as Direct Hit +25%, Brotherhood +5%) and always has a variance of ±5%..
        /// </summary>
        internal static string Tooltips_tooltips_Expected_Damage {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Expected_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Defense.
        /// </summary>
        internal static string Tooltips_tooltips_Magic_Defense {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Magic_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  reduces magic damage taken by 1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Magic_Defense_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Magic_Defense_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Stat.
        /// </summary>
        internal static string Tooltips_tooltips_Main_Stat {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Main_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  increases damage dealt as well as HP restored by your actions.
        ///An increase of 10% main stat constitutes a 10% increase in damage and healing.
        ///
        ///SMNs physick is the only exception since it scales with MND instead of INT..
        /// </summary>
        internal static string Tooltips_tooltips_Main_Stat_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Main_Stat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  point(s).
        ///To reach the next tier you need .
        /// </summary>
        internal static string Tooltips_tooltips_Next_Tier {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Next_Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piety.
        /// </summary>
        internal static string Tooltips_tooltips_Piety {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Piety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  increases the amount of MP gained per server tick (every 3s).
        ///By default you will gain 200 MP per tick.
        ///
        ///Piety gives 1 extra MP approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Piety_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Piety_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  point(s)..
        /// </summary>
        internal static string Tooltips_tooltips_points {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill/Spell Speed.
        /// </summary>
        internal static string Tooltips_tooltips_Skill_Spell_Speed {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Skill_Spell_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  point(s).
        ///
        ///DoT damage increases by 0.1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Skill_Spell_Speed_DoT_Increase {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Skill_Spell_Speed_DoT_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  shortens cast times and recast timers as well as increase damage done by damage over time effects.
        ///
        ///A 2.5s GCD is sped up by 0.01s approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Skill_Spell_Speed_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Skill_Spell_Speed_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Speed.
        /// </summary>
        internal static string Tooltips_tooltips_Spell_Speed {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Spell_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  point(s).
        ///
        ///A 2.8s GCD is sped up by 0.01s approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Spell_Speed_GCD {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Spell_Speed_GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenacity.
        /// </summary>
        internal static string Tooltips_tooltips_Tenacity {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Tenacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  increases damage dealt and HP restored by your own actions as well as reducing damage taken.
        ///
        ///Tenacity&apos;s effect increases by 0.1% approx. every .
        /// </summary>
        internal static string Tooltips_tooltips_Tenacity_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Tenacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Tooltips_tooltips_Vitality {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  increases max HP by .
        /// </summary>
        internal static string Tooltips_tooltips_Vitality_Tooltip_1 {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Vitality_Tooltip_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  every point.
        ///As a .
        /// </summary>
        internal static string Tooltips_tooltips_Vitality_Tooltip_2 {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Vitality_Tooltip_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  you have .
        /// </summary>
        internal static string Tooltips_tooltips_Vitality_Tooltip_3 {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Vitality_Tooltip_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  base HP..
        /// </summary>
        internal static string Tooltips_tooltips_Vitality_Tooltip_4 {
            get {
                return ResourceManager.GetString("Tooltips_tooltips_Vitality_Tooltip_4", resourceCulture);
            }
        }
    }
}
