//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterPanelRefined {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterPanelRefined.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Panel Refined Config.
        /// </summary>
        internal static string Config_Character_Panel_Refined_Config {
            get {
                return ResourceManager.GetString("Config_Character_Panel_Refined_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply any config changes you must reopen the character panel..
        /// </summary>
        internal static string Config_Help_Apply_Changes {
            get {
                return ResourceManager.GetString("Config_Help_Apply_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override default tooltips.
        /// </summary>
        internal static string Config_Override_default_tooltips {
            get {
                return ResourceManager.GetString("Config_Override_default_tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the default tooltips for all stats..
        /// </summary>
        internal static string Config_Override_default_tooltips_tooltip {
            get {
                return ResourceManager.GetString("Config_Override_default_tooltips_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show average damage.
        /// </summary>
        internal static string Config_Show_average_damage {
            get {
                return ResourceManager.GetString("Config_Show_average_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show average healing.
        /// </summary>
        internal static string Config_Show_average_healing {
            get {
                return ResourceManager.GetString("Config_Show_average_healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show crit damage increase.
        /// </summary>
        internal static string Config_Show_crit_damage_increase {
            get {
                return ResourceManager.GetString("Config_Show_crit_damage_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show direct hit damage increase.
        /// </summary>
        internal static string Config_Show_direct_hit_damage_increase {
            get {
                return ResourceManager.GetString("Config_Show_direct_hit_damage_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Game Language if available.
        /// </summary>
        internal static string Config_Use_Game_Language_if_available {
            get {
                return ResourceManager.GetString("Config_Use_Game_Language_if_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the internal game language for this plugin if available. 
        /// Currently Available: English, German, French.
        /// </summary>
        internal static string Config_Window_Use_Game_Language_Tooltip {
            get {
                return ResourceManager.GetString("Config_Window_Use_Game_Language_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Chance.
        /// </summary>
        internal static string Panel_Crit_Chance {
            get {
                return ResourceManager.GetString("Panel_Crit_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Damage.
        /// </summary>
        internal static string Panel_Crit_Damage {
            get {
                return ResourceManager.GetString("Panel_Crit_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage &amp; Mitigation.
        /// </summary>
        internal static string Panel_Damage_and_Mitigation {
            get {
                return ResourceManager.GetString("Panel_Damage_and_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Increase.
        /// </summary>
        internal static string Panel_Damage_Increase {
            get {
                return ResourceManager.GetString("Panel_Damage_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Damage.
        /// </summary>
        internal static string Panel_Damage_per_100_Potency {
            get {
                return ResourceManager.GetString("Panel_Damage_per_100_Potency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Hit Chance.
        /// </summary>
        internal static string Panel_Direct_Hit_Chance {
            get {
                return ResourceManager.GetString("Panel_Direct_Hit_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire IV Cast.
        /// </summary>
        internal static string Panel_Fire_IV_GCD {
            get {
                return ResourceManager.GetString("Panel_Fire_IV_GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recast.
        /// </summary>
        internal static string Panel_GCD {
            get {
                return ResourceManager.GetString("Panel_GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Healing.
        /// </summary>
        internal static string Panel_Heal_per_100_Potency {
            get {
                return ResourceManager.GetString("Panel_Heal_per_100_Potency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Mitigation.
        /// </summary>
        internal static string Panel_Magic_Mitigation {
            get {
                return ResourceManager.GetString("Panel_Magic_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana per Tick.
        /// </summary>
        internal static string Panel_Mana_per_Tick {
            get {
                return ResourceManager.GetString("Panel_Mana_per_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Mitigation.
        /// </summary>
        internal static string Panel_Physical_Mitigation {
            get {
                return ResourceManager.GetString("Panel_Physical_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Increase.
        /// </summary>
        internal static string Panel_Skill_Speed_Increase {
            get {
                return ResourceManager.GetString("Panel_Skill_Speed_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Properties.
        /// </summary>
        internal static string Panel_Speed_Properties {
            get {
                return ResourceManager.GetString("Panel_Speed_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Critical Hit{@Clear} affects the rate at which your attacks and heals can critically hit as well as the damage dealt and HP restored by a critical hit.
        ///
        ///Critical Hit Rate and Damage increase by 0.1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Crit_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Crit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Defense{@Clear} reduces physical damage taken by 1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Defense_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Defense_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Determination{@Clear} increases damage dealt by attacks as well as HP restored by healing actions.
        ///
        ///Determination&apos;s effect increases by 0.1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Determination_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Determination_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Direct Hit Rate{@Clear} affects the rate at which your attacks can direct hit.
        ///A direct hit increases damage done by 25%.
        ///
        ///Direct Hit Rate increases by 0.1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Direct_Hit_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Direct_Hit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average damage of a 100 potency skill, including critical and direct hits as well as passive traits such as Maim and Mend.
        ///
        ///A normal attack will do {@Highlight}{NormalValue}{@Clear} damage.
        ///A critical hit will do {@Highlight}{CritValue}{@Clear} damage.
        ///
        ///Damage always has a variance of ±5%..
        /// </summary>
        internal static string Tooltips_Expected_Damage {
            get {
                return ResourceManager.GetString("Tooltips_Expected_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average HP restored by a 100 potency healing action, including critical hits as well as passive traits such as Maim and Mend.
        ///
        ///A normal heal will restore {@Highlight}{NormalValue}{@Clear} HP.
        ///A critical hit will restore {@Highlight}{CritValue}{@Clear} HP.
        ///
        ///HP restored will always vary by ±3%..
        /// </summary>
        internal static string Tooltips_Expected_Heal {
            get {
                return ResourceManager.GetString("Tooltips_Expected_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Magic Defense{@Clear} reduces magic damage taken by 1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Magic_Defense_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Magic_Defense_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Main Stat{@Clear} increases damage dealt as well as HP restored by your actions.
        ///An increase of 10% main stat constitutes a 10% increase in damage and healing.
        ///
        ///SMNs physick is the only exception since it scales with MND instead of INT..
        /// </summary>
        internal static string Tooltips_Main_Stat_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Main_Stat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reach the next tier you need {@Highlight}{NextTier}{@Clear} points..
        /// </summary>
        internal static string Tooltips_Next_Tier {
            get {
                return ResourceManager.GetString("Tooltips_Next_Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Piety{@Clear} increases the amount of MP gained per server tick (every 3s).
        ///By default you will gain 200 MP per tick.
        ///
        ///Piety gives 1 extra MP every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Piety_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Piety_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoT damage increases by 0.1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Skill_Spell_Speed_DoT_Increase {
            get {
                return ResourceManager.GetString("Tooltips_Skill_Spell_Speed_DoT_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Skill/Spell Speed{@Clear} shortens cast times and recast timers as well as increase damage done by damage over time effects.
        ///
        ///A 2.5s GCD is sped up by 0.01s on average every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Skill_Spell_Speed_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Skill_Spell_Speed_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 2.8s GCD is sped up by 0.01s on average every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Spell_Speed_28_GCD {
            get {
                return ResourceManager.GetString("Tooltips_Spell_Speed_28_GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Tenacity{@Clear} increases damage dealt and HP restored by your own actions as well as reducing damage taken.
        ///
        ///Tenacity&apos;s effect increases by 0.1% every {PointsPerTier} points..
        /// </summary>
        internal static string Tooltips_Tenacity_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Tenacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {@Title}Vitality{@Clear} increases max HP by {HpPerPoint} every point.
        ///As a {Job} you have {BaseHp} base HP..
        /// </summary>
        internal static string Tooltips_Vitality_Tooltip {
            get {
                return ResourceManager.GetString("Tooltips_Vitality_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently wasting {@Wasting}{Wasting}{@Clear} {Points}..
        /// </summary>
        internal static string Tooltips_Wasting {
            get {
                return ResourceManager.GetString("Tooltips_Wasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        internal static string Tooltips_Wasting_Points_Plural {
            get {
                return ResourceManager.GetString("Tooltips_Wasting_Points_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        internal static string Tooltips_Wasting_Points_Singular {
            get {
                return ResourceManager.GetString("Tooltips_Wasting_Points_Singular", resourceCulture);
            }
        }
    }
}
